### ISSUE TITLE
Figure out how we're going to translate interactive texts

### ISSUE THREAD

**Issue by sepsol** [codeforsanjose/project-happening-atm#127]
## The Problem:
We have situations where a part of a text has an *email address* which needs to be clickable as `<a>` tags or part of a text is in *quotation marks* which for has to be wrapped in `&quot;`. Since we are providing the text from our yaml translation files, we have to figure out a way to resolve situations like this.

### Files that are affected as of 8f2b4ef07b9cc6c0df87f18f2853b4ab5fa8663c:
* `frontend/src/components/MeetingView/ParticipateView/OldParticipatePages.jsx`
* `frontend/src/components/MeetingView/ParticipateView/OldParticipatePages/ParticipateJoin.jsx`
* `frontend/src/components/MeetingView/ParticipateView/OldParticipatePages/ParticipateRequest.jsx`
* `frontend/src/components/MeetingView/ParticipateView/ParticipateView.jsx`

### Possible Solutions:
* Introduce variables in our translation `yaml` files.
* Create another custom hook that wraps around the `useTranslation` hook from `react-i18next` package, which analyzes the text and tries to find stuff like quotation marks and links from it.

**Comment by jeffersonken19** [comment]
![Uploading Screen Shot 2021-02-09 at 7.50.41 PM.png…]()
