### ISSUE TITLE
Admin: Different contents when I am logged in as admin than I would as a community member

### ISSUE THREAD

**Issue by cfsjsharedadmin** [codeforsanjose/project-happening-atm#164]
We need to hide/show the admin components based on how we are checking authentication/authorization

**Comment by jerrycyip** [comment]
Can we distinguish the difference b/w this issue and issue 113? (https://github.com/codeforsanjose/gov-agenda-notifier/issues/113). Only admins can view the "create meeting" button (and the subsequent create meeting flow w/ modal etc.) so there appears to be some overlap in these 2 issues unless someone can differentiate/distinguish the scope between the 2.

**Comment by anna-kartynnik** [comment]
In my opinion, #113 is about adding that "Create New Meeting" flow, but this issue is about showing different content or actions depending on a user's role across the whole app.

**Comment by jerrycyip** [comment]
sounds good - agreed.  Indeed I do see now other admin content/functionality on the mockups (such as "Upload New Agenda" / "Delete Meeting" / "Delete Agenda" etc.) that is not part of the create meeting flow and could apply for this issue if not elsewhere.  That works for me.  Pardon my earlier concerns, just wanted to avoid duplicative work = )
