### ISSUE TITLE
Agenda: View the Agenda Item's Recommendation

### ISSUE THREAD

**Issue by feliciafalafelc** [codeforsanjose/project-happening-atm#190]
View the Agenda Item's Recommendation

**Comment by jerrycyip** [comment]
Can you elaborate on what is meant by "Agenda item's Recommendation"?  Is there documentation on what that is?  I'm fairly new to the project so perhaps I'm missing it, but I don't see a requirement or mockup referring to what comprises an "Agenda item's recommendation"...

**Comment by jerrycyip** [comment]
This mockup is what all I could find on "Recommendations": https://xd.adobe.com/view/a33388a1-5e85-4b22-8f03-a8d5f979dacf-f660/screen/2a2c0d66-d79f-4877-bad7-255c0206d7ed/

Is that what you are referring to by chance?  If so, my initial assessment is this appears to first require a backend change as there is no "recommendation" field currently anywhere in the graphql queries nor mutations
