### ISSUE TITLE
Frontend Login View

### ISSUE THREAD

**Issue by aaa12345678910** [codeforsanjose/project-happening-atm#42]
Frontend Login View 

Support Google SSO

**Comment by jeffersonken19** [comment]
Andrew merged in the Google Auth.

**Comment by cfsjsharedadmin** [comment]
MS Auth is almost done & Sepehr provided the MS test account
Email & password is almost done.
Password reset is not complete yet.

**Comment by cfsjsharedadmin** [comment]
What data does the frontend need from the auth session? Just the token?

**Comment by cfsjsharedadmin** [comment]
Do we support a logout button? That means we need to have a token blacklist or just delete the auth token from the client cookies.

Or do we just timeout their session? Right now it is set to an hour.

Let's go with deleting the auth token from the client from now.
